services:
  - type: web
    name: timus-backend
    runtime: python
    rootDir: timus-main/backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
